name: merge request

on:
  pull_request:
    inputs:
      xcodeproj_path:
        required: false
        type: string
      scheme_name:
        required: false
        type: string

jobs:
  swiftformat:
    runs-on: ubuntu-latest
    container: ghcr.io/nicklockwood/swiftformat:0.49.18
    steps:
      - uses: actions/checkout@v3
      - name: SwiftFormat Lint Run
        run: swiftformat . --lint --config .swiftformat

  swiftlint:
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:0.47.0
    steps:
      - uses: actions/checkout@v3
      - name: Swiftlint Run
        working-directory: ASDKSample
        run: swiftlint --quiet

  check:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2

      - name: Bundle install
        run: bundle install

      - name: build Package.swift
        run: bundle exec fastlane build_spm

      - name: tests lint
        env:
          XCODEPROJ_PATH: ${{ inputs.xcodeproj_path }}
          SCHEME_NAME: ${{ inputs.scheme_name }}
        run: bundle exec fastlane check
    
  # check:
  #   uses: tinkoff-mobile-tech/workflows/.github/workflows/ios_lib.merge_request.yml@v1
